---
title: "Mass Emissions Data"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(shiny)
library(flexdashboard)
library(leaflet)
library(dplyr)
library(ggplot2)
library(DT)
library(geojsonio)

# Load geojson of LA County watersheds.
# Make sure full file path is included if not nested in your working directory.
watersheds <- geojsonio::geojson_read("json/watersheds.json", what = "sp")

# Create a color palette 'pal' for watersheds
pal <- colorFactor(palette = c("#1F77B4", "#AEC7E8", "#FF7F0E", "#FFBB78", 
                               "#2CA02C", "#98DF8A", "#D62728", "#FF9896", 
                               "#9467BD", "#C5B0D5", "#8C564B", "#C49C94", 
                               "#E377C2", "#F7B6D2", "#7F7F7F", "#C7C7C7", 
                               "#BCBD22", "#DBDB8D", "#17BECF", "#9EDAE5"), 
                   domain = NULL)

stations <- read.csv("data/stations.csv")
```

Column {.tabset data-width=650}
-----------------------------------------------------------------------

### Map

```{r}
station_icon <- makeIcon("icons/blue-circle.png", iconWidth = 12, iconHeight = 12)

leaflet::renderLeaflet({
  leaflet::leaflet() %>%
  leaflet::addProviderTiles("Hydda.Full") %>%
  leaflet::setView(-118.2437, 34.0522, zoom = 9) %>%
  leaflet::addPolygons(data=watersheds, stroke = TRUE, weight = 0.25, 
                       smoothFactor = 0.5, fillOpacity = 0.35,
                       fillColor = ~pal(NAME), 
                       popup = ~paste("", NAME, "", "")) %>%
  leaflet::addMarkers(data=stations, icon = station_icon,
                      popup = ~paste("<b>Station Code</b>:", stations$StationCode, "<br>",
                                     "<b>Alternate Station Names</b>: - <br>",
                               "<b>Waterbody</b>:", stations$Waterbody, "<br>",
                               "<b>Watershed</b>: ", stations$Watershed, "<br>",
                               "<b>Description:</b>", stations$Description, "<br>"))
})

```

### Monitoring Data

```{r}
DT::renderDataTable({
  DT::datatable()
})

```

Inputs {.sidebar data-width=300}
-----------------------------------------------------------------------

### Instructions

Select a station from the map on the left to retrieve monitoring data. You can use the bottom selector to plot particular constituents from that station.

```{r}
selectInput("Pollutant", label = h4("Pollutant"), 
    choices = list("-" = "-"),
    selected = "-")
```


#### Plot

```{r}
shiny::renderPlot({
  ggplot2::ggplot()
})

```

